- name: Change owner Redmine directory
  sudo: yes
  command:
    chown -R www-data:www-data {{ redmine_dir }}

- name: Enable Mod Header
  sudo: yes
  command:
    a2enmod headers

- name: Restart apache2
  sudo: yes
  service: name=apache2 state=restarted

- name: Run apache2 automatically at boot time
  sudo: yes
  service: name=apache2 state=started enabled=yes
