- name: Create swap area
  sudo: yes
  command: dd if=/dev/zero of=/swap bs=1M count=1024

- name: Make swap memory
  sudo: yes
  command: mkswap /swap

- name: Turn on swap memory
  sudo: yes
  command: swapon /swap

- name: Create Japanese locale
  sudo: yes
  locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: Install required packages
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libcurl4-openssl-dev
    - postgresql
    - postgresql-server-dev-9.5
    - python-psycopg2
    - apache2
    - apache2-dev
    - libapr1-dev
    - libaprutil1-dev
    - imagemagick
    - libmagick++-dev
    - fonts-ipafont-gothic
    - subversion
    - git
    - postfix

- name: Start Postfix service
  sudo: yes
  service: name=postfix state=started enabled=yes

- name: Create Security Token script
  sudo: yes
  template: src=S81redmine dest=/etc/rc3.d/S81redmine mode=0755
